operations:
  dataSource:
    cat-h2:
      driver-class-name: com.mysql.jdbc.Driver
      username: ${embedded.mysql.user}
      password: ${embedded.mysql.password}
      url: jdbc:mysql://localhost:${embedded.mysql.port}/${embedded.mysql.database}
      schema: classpath:mysql/test-cat-schema.mysql.sql
    dog-h2:
      driver-class-name: com.mysql.jdbc.Driver
      username: ${embedded.mysql.user}
      password: ${embedded.mysql.password}
      url: jdbc:mysql://localhost:${embedded.mysql.port}/${embedded.mysql.database}
      schema: classpath:mysql/test-dog-schema.mysql.sql
    #sample for tests to verify it doesn't fail on missing schema
    tortoise-h2:
      driver-class-name: com.mysql.jdbc.Driver
      username: ${embedded.mysql.user}
      password: ${embedded.mysql.password}
      url: jdbc:mysql://localhost:${embedded.mysql.port}/${embedded.mysql.database}
  procedures:
    create-cat:
      sql: |
        INSERT INTO CAT (NAME, LAST_NAME) VALUES (:name, :lastName)
      parameters:
        name:
          key: name
          type: VARCHAR
        lastName:
          key: lastName
          type: VARCHAR
    create-dog:
      sql: |
        INSERT INTO DOG (NAME, LAST_NAME) VALUES (:name, :lastName)
      parameters:
        name:
          key: name
          required: true
          type: VARCHAR
        lastName:
          key: lastName
          type: VARCHAR
embedded:
  mysql:
    enabled: true
    user: test
    #this password can't be changed as overridden by mysqlProperties class fields and other props I assume
    password: test
    database: test_db
  postgresql:
    enabled: false
spring:
  h2:
    console:
      enabled: true