operations:
  dataSource:
    cat-h2:
      driver-class-name: org.postgresql.Driver
      username: ${embedded.postgresql.user}
      password: ${embedded.postgresql.password}
      url: jdbc:postgresql://localhost:${embedded.postgresql.port}/${embedded.postgresql.database}
      schema: classpath:postgresql/test-cat-schema.postgresql.sql
    dog-h2:
      driver-class-name: org.postgresql.Driver
      username: ${embedded.postgresql.user}
      password: ${embedded.postgresql.password}
      url: jdbc:postgresql://localhost:${embedded.postgresql.port}/${embedded.postgresql.database}
      schema: classpath:postgresql/test-dog-schema.postgresql.sql
    #sample for tests to verify it doesn't fail on missing schema
    tortoise-h2:
      driver-class-name: org.postgresql.Driver
      username: ${embedded.postgresql.user}
      password: ${embedded.postgresql.password}
      url: jdbc:postgresql://localhost:${embedded.postgresql.port}/${embedded.postgresql.database}
  procedures:
    create-cat:
      sql: |
        INSERT INTO CAT (NAME, LAST_NAME) VALUES (:name, :lastName)
      parameters:
        name:
          key: name
          type: VARCHAR
        lastName:
          key: lastName
          type: VARCHAR
    create-dog:
      sql: |
        INSERT INTO DOG (NAME, LAST_NAME) VALUES (:name, :lastName)
      parameters:
        name:
          key: name
          required: true
          type: VARCHAR
        lastName:
          key: lastName
          type: VARCHAR
embedded:
  postgresql:
    enabled: true
    user: postgresql
    #this password can't be changed as overridden by PostgreSQLProperties class fields and other props I assume
    password: letmein
    database: test_db
  mysql:
    enabled: false
spring:
  h2:
    console:
      enabled: true