operations:
  dataSource:
    cat:
      driver-class-name: com.mysql.jdbc.Driver
      username: ${embedded.mysql.user}
      password: ${embedded.mysql.password}
      url: jdbc:mysql://localhost:${embedded.mysql.port}/${embedded.mysql.database}
      schema: classpath:mysql/test-cat-schema.mysql.sql
    dog:
      driver-class-name: com.mysql.jdbc.Driver
      username: ${embedded.mysql.user}
      password: ${embedded.mysql.password}
      url: jdbc:mysql://localhost:${embedded.mysql.port}/${embedded.mysql.database}
      schema: classpath:mysql/test-dog-schema.mysql.sql
    #sample for tests to verify it doesn't fail on missing schema
    tortoise:
      driver-class-name: com.mysql.jdbc.Driver
      username: ${embedded.mysql.user}
      password: ${embedded.mysql.password}
      url: jdbc:mysql://localhost:${embedded.mysql.port}/${embedded.mysql.database}
  procedures:
    create-cat:
      sql: |
        insert into cat (name, last_name) values (:name, :lastName)
      parameters:
        name:
          key: name
          type: VARCHAR
        lastName:
          key: lastName
          type: VARCHAR
    create-dog:
      sql: |
        insert into dog (name, last_name) values (:name, :lastName)
      parameters:
        name:
          key: name
          required: true
          type: VARCHAR
        lastName:
          key: lastName
          type: VARCHAR