operations:
  properties:
    cat:
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: ${embedded.mysql.user}
        password: ${embedded.mysql.password}
        url: jdbc:mysql://localhost:${embedded.mysql.port}/${embedded.mysql.database}
      sql:
        schema-locations:
          - classpath:mysql/test-cat-schema.mysql.sql
    dog:
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: ${embedded.mysql.user}
        password: ${embedded.mysql.password}
        url: jdbc:mysql://localhost:${embedded.mysql.port}/${embedded.mysql.database}
      sql:
        schema-locations:
          - classpath:mysql/test-dog-schema.mysql.sql
    #sample for tests to verify it doesn't fail on missing schema
    tortoise:
      datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: ${embedded.mysql.user}
        password: ${embedded.mysql.password}
        url: jdbc:mysql://localhost:${embedded.mysql.port}/${embedded.mysql.database}
  procedures:
    create-cat:
      sql: |
        insert into cat (name, last_name) values (:name, :lastName)
      parameters:
        name:
          key: name
          type: VARCHAR
        lastName:
          key: lastName
          type: VARCHAR
    create-dog:
      sql: |
        insert into dog (name, last_name) values (:name, :lastName)
      parameters:
        name:
          key: name
          required: true
          type: VARCHAR
        lastName:
          key: lastName
          type: VARCHAR