CREATE SEQUENCE cat_id_seq;

CREATE TABLE IF NOT EXISTS CAT(ID INT NOT NULL PRIMARY KEY default nextval('cat_id_seq'), NAME VARCHAR(255), LAST_NAME VARCHAR(255));

ALTER SEQUENCE cat_id_seq OWNED BY cat.id;