CREATE SEQUENCE dog_id_seq;

CREATE TABLE IF NOT EXISTS DOG(ID INT NOT NULL PRIMARY KEY default nextval('dog_id_seq'), NAME VARCHAR(255), LAST_NAME VARCHAR(255));

ALTER SEQUENCE dog_id_seq OWNED BY dog.id;